# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160719_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
