# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='tituloC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
