# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comentario_tituloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='slugC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
